### ISSUE TITLE
ImportError: cannot import name 'models' from 'trecs'

### ISSUE THREAD

**Issue by eperrier** [elucherini/t-recs#100]
Hi, I received the following error when trying to import trecs:

`1

import trecs

2

​

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-81f55b587a73> in <module>
----> 1 import trecs

/opt/conda/lib/python3.7/site-packages/trecs/__init__.py in <module>
      1 """ T-RECS simulation package """
----> 2 from trecs import models, base, components, metrics, random
      3 from .logging import VerboseMode

ImportError: cannot import name 'models' from 'trecs' (/opt/conda/lib/python3.7/site-packages/trecs/__init__.py)

`

The installation is via a Singularity container pulling the Ubuntu 20.04 dockerfile with Anaconda3-2020.02-Linux-x86_64.sh. 

trecs is then installed using pip.

The same error arose using Google colab. 

Suggestions for fixes welcome. Is there a dockerfile or image available?

**Comment by sunnymatt** [comment]
@eperrier Thank you for bringing this to our attention - I'm able to reproduce the error in a fresh conda environment, although strangely I do not get this error on my existing installation. Investigating now and will push a fix ASAP 🙂

**Comment by sunnymatt** [comment]
@eperrier Please try installing from `pip` again - I think the problem should be fixed now. 😃
