### ISSUE TITLE
Adding items at run time: introduce threshold on number of items left

### ISSUE THREAD

**Issue by elucherini** [elucherini/t-recs#31]
The current behavior is:
**Not enough items left?** Add new items (default value: `2*num_items_per_iter`).

A better option is to add new items when the number of items left falls below a threshold:
**Number of items left < threshold?** Add new items (default value: multiple of the threshold?).

**Comment by sunnymatt** [comment]
Closing this issue because this is no longer the default behavior - @elucherini please feel free to reopen if I misunderstood!
