### ISSUE TITLE
Metrics should not provide an initial value of None

### ISSUE THREAD

**Issue by sunnymatt** [elucherini/t-recs#86]
Currently all metrics are initialized with a value of `None`, which makes them a bit difficult to work with out of the box; users have to call `get_measurements()` and then manually filter out the `None` value before doing things like plotting values or visualizing the results of the simulation

**Comment by elucherini** [comment]
Ok so I briefly looked into this and the reason why most metrics are initialized with `None` is to accommodate `DiffusionTreeMeasurement`. My reasoning was: while most metrics are not really meaningful at step zero, `DiffusionTreeMeasurement ` has an actual value at the beginning (equal to the number of nodes in the tree iirc). This is just to add context, not to claim this solution is a good one lol.

**Comment by sunnymatt** [comment]
Closed with #97 ! For now we have made it easier to declare what's going on in the code at the step before the simulation starts by providing the entire `recommender` object 👍  We should feel free to return to this / update the API, but now I feel comfortable that it is reasonably clear
